apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceaccount }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterrole }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", "get"]
- apiGroups:
  - network-checker.ext
  resources:
  - agents
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.clusterrolebinding }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.clusterrole }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceaccount }}
    namespace: {{ .Release.Namespace }}
